category_classification_task:
  description: >
    Pre-defined categories:
    1. YC Agents Hackathon
    2. Open Source
    3. Startup Founder

    1. For each tweet, classify it into one of the 3 categories you identified.
    2. For each category, with the help of the identify_top_tweet_task, identify the top 3 tweets with the highest engagement (likes + retweets + replies).

  expected_output: "TopTweets"
  agent: "category_classification_agent"

identify_top_tweet_task:
  description: >
    From the provided list of trending tweets, identify the tweet with the highest engagement.
    Engagement is defined as the sum of likes, retweets, and replies.
    
    Return the tweet object that has the highest engagement score.
  expected_output: "TopTweets"
  agent: "top_tweets_identifier_agent"